version: '3.8'
services:
  zetachain_mainnet_rpc:
    platform: linux/amd64
    image: zetachain/zetacored:${DOCKER_TAG:-ubuntu-v14.0.1.0}
    container_name: zetachain_mainnet_rpc
    environment:
      DAEMON_HOME: "/root/.zetacored"
      NETWORK: mainnet
      RESTORE_TYPE: "snapshot"
      SNAPSHOT_API: https://snapshots.zetachain.com
      TRUST_HEIGHT_DIFFERENCE_STATE_SYNC: 40000
      CHAIN_ID: "zetachain_7000-1"
      VISOR_NAME: "cosmovisor"
      DAEMON_NAME: "zetacored"
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "false"
      DAEMON_RESTART_AFTER_UPGRADE: "true"
      UNSAFE_SKIP_BACKUP: "true"
      CLIENT_DAEMON_NAME: "zetaclientd"
      CLIENT_DAEMON_ARGS: ""
      CLIENT_SKIP_UPGRADE: "true"
      CLIENT_START_PROCESS: "false"
      MONIKER: mainnet-docker-rpc
      #If this is true it will erase everything and start over from scratch.
      RE_DO_START_SEQUENCE: "false"
      #If this is true it will build the dockerfile and use binary from built docker file instead of remote docker image for local development testing on non-governance upgrades.
      IS_LOCAL_DEVELOPMENT: "false"
    ports:
      - "26656:26656"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
      - "26657:26657"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - zetacored_data_mainnet:/root/.zetacored/
    entrypoint: bash /scripts/start.sh
volumes:
  zetacored_data_mainnet:
