version: '3.8'
services:
  zetachain_athens3_rpc:
    platform: linux/amd64
    build:
      context: ../../..
      dockerfile: Dockerfile
    environment:
      DAEMON_HOME: "/root/.zetacored"
      NETWORK: athens3
      RESTORE_TYPE: "snapshot"
      SNAPSHOT_API: https://snapshots.zetachain.com
      TRUST_HEIGHT_DIFFERENCE_STATE_SYNC: 40000
      CHAIN_ID: "athens_7001-1"
      VISOR_NAME: "cosmovisor"
      DAEMON_NAME: "zetacored"
      DAEMON_ALLOW_DOWNLOAD_BINARIES: "false"
      DAEMON_RESTART_AFTER_UPGRADE: "false"
      UNSAFE_SKIP_BACKUP: "true"
      CLIENT_DAEMON_NAME: "zetaclientd"
      CLIENT_DAEMON_ARGS: ""
      CLIENT_SKIP_UPGRADE: "true"
      CLIENT_START_PROCESS: "false"
      MONIKER: testnet-docker-rpc
      #If this is true it will erase everything and start over from scratch.
      RE_DO_START_SEQUENCE: "false"
      #If this is true it will build the dockerfile and use binary from built docker file instead of remote docker image for local development testing on non-governance upgrades.
      IS_LOCAL_DEVELOPMENT: "true"
    ports:
      - "26656:26656"
      - "1317:1317"
      - "8545:8545"
      - "8546:8546"
      - "26657:26657"
      - "9090:9090"
      - "9091:9091"
    volumes:
      - zetacored_data_athens3:/root/.zetacored/
      - ../../../contrib/docker-scripts/start.sh:/scripts/start.sh
    entrypoint: bash /scripts/start.sh

volumes:
  zetacored_data_athens3:
